name: anythingllm

networks:
  traefik_proxy:
    driver: bridge

services:
  anything-llm:
    container_name: anythingllm
    labels:
      - traefik.enable=true
      - traefik.http.routers.llm.rule=Host(`llm.uivale.com`)
      - traefik.http.routers.llm.entrypoints=websecure
      - traefik.http.routers.llm.tls=true
      - traefik.http.routers.llm.tls.certresolver=mytlschallenge
      - traefik.http.services.llm.loadbalancer.server.port=3001
      - traefik.docker.network=traefik_proxy
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
      - "../frontend/public/embed/:/app/frontend/public/embed"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - traefik_proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
